#!/bin/bash

file=$1

if [[ ! -f "$file" ]]; then
  echo "File does not exist."
  exit 1
fi

declare -a lines

while IFS= read -r line; do
  lines=("$line" "${lines[@]}")
done < "$file"

for line in "${lines[@]}"; do
  echo "$line"
done