#!/bin/bash
# Crear un script donde se ingrese una serie de números enteros y se devuelva la suma
# de los mismos, se permitirá el ingreso de un máximo de 10 números y solo se deben sumar
# los argumentos válidos (los que representen un número).
# Tips: utilizar shift y esta expresión regular
# ES_NUMERO='^-?[0-9]+$'

suma=0
contador=0
NUM='^-?[0-9]+$'
A="*"
while [ $contador -le 10 ]; do
  read -p "Ingrese un número entero (* para finalizar): " numero
  if [[ "$numero" == "$A" ]]; then
  echo "salimos"
    break
  fi
  if [[ $numero =~ $NUM ]]; then
    suma=$(($suma + $numero))
    contador=$(($contador + 1))
  else
    echo "Valor inválido. Intente nuevamente."
  fi
done

echo "La suma de los números es: $suma"


