#!/bin/bash
#Construya un script que reciba una cadena, el script debe validar si la cadena ingresada es una dirección IP válida.
#Ejemplo de dirección IP válida: 192.168.0.1 (son cuatro enteros entre 0 y 255 separados por punto)

CADENA=$1

IP1='^([0-9]{1,3}\.){3}[0-9]{1,3}$'
A=$(echo $CADENA | cut -d"." -f1)
B=$(echo $CADENA | cut -d"." -f2)
C=$(echo $CADENA | cut -d"." -f3)
D=$(echo $CADENA | cut -d"." -f4)
echo $A $B $C $D

NUM=($A $B $C $D)

for i in "${NUM[@]}"; do
  if ! [[ $i =~ $IP1 ]] || (( "$i" < 0 )) || (( "$i" > 255 )); then
    echo "La cadena ingresada no es una dirección IP válida."
    echo $i 
    exit
    
  fi
done
echo "La cadena ingresada es una dirección IP válida."