#!/bin/bash

#Cree una función que imprima “¡Hola, mundo!” cuando se llame.

function saludo() {
echo ¡Hola, mundo!
}

if [ $# -ne 0 ]; then
        echo "Error: Esta función no acepta argumentos."
        exit 1
fi

saludo=$(saludo)
echo $saludo