#!/bin/bash
#Cree una función que tome una cadena como argumento y devuelva la cadena en orden inverso.

function inverso() {
    cadena=$1
    longitud=${#cadena}
    invertida=""
    for ((i = longitud - 1; i >= 0; i--)); do
        invertida="${invertida}${cadena:i:1}"
    done
    echo $invertida
}

inverso $1