#!/bin/bash

#a) Deberá ingresarse en formato dd-mm-aaaa (guión incluido) la fecha en que nació y el
#script retornará el día de la semana de dicha fecha.
#Nota: La fecha introducida debe ser válida, el script verificará esto, en caso de fecha inválida el script aborta comentando dicha situación. Puede ser útil el comando date.

read -p "Ingrese fecha de cumpleaños en el formato aaaa-mm-dd (guión incluido)" fecha
regex="^[0-9]{4}-[0-9]{2}-[0-9]{2}$"

[[ ! $fecha =~ $regex ]] && echo "El formato no es el válido, por favor ingrese dd-mm-aaaa (guión incluido)" && exit 1

dia_semana=$(date -d "$fecha" +"%A")

echo "El día de la semana de la fecha $fecha es: $dia_semana"

#Días vividos. Deberá ingresarse en formato dd-mm-aaaa la fecha en que nació, el script deberá retornar la cantidad de días transcurridos hasta la fecha.
#Nota: La fecha introducida debe ser válida, en caso contrario el programa aborta

fecha_ingresada=$(date -d $fecha +%s)
fecha_actual=$(date +%s)

cantidad_dias=$(( ($fecha_actual - $fecha_ingresada)/86400 ))
echo "La cantidad de dias que viviste fue: $cantidad_dias"