#!/bin/bash

n=$1

[ $n -le 0 ] && echo "Debe ser numero positivo" && exit 1

cont=0
for (( i=2; i<=n; i+=2 )); do
    ((cont++))
done
echo "Hay $cont numeros pares del 1 a $n"
cont1=0
for (( i=1; i<=n; i+=2 )); do
    ((cont1++))
done
echo "Hay $cont1 numeros impares del 1 a $n"