#!/bin/bash

#Crear un script que reciba como argumentos una cantidad de palabras.
#El script debe determinar cuántas palabras son y cuántas de ellas tienen al menos 3 caracteres.
#En caso de no suministrarse argumentos, deberá indicar que sin argumentos el script no puede generar resultados.

[ $# -eq 0 ] && echo "El script solo funciona con argumentos" && exit 1

echo "Total palabras: $#"
cont=0
for palabra in $@; do
if [[ ${#palabra} -eq 3 ]]; then
    ((cont++))
fi
done
echo "El total de palabras con solo 3 caracteres fue: $cont"