#!/bin/bash

#Crear un script que reciba como argumentos una cantidad de palabras.
#El script debe determinar cuántas palabras son y cuántas de ellas tienen al menos 3 caracteres.
#En caso de no suministrarse argumentos, deberá indicar que sin argumentos el script no puede generar resultados.
¨

while : ; do
    read -p "Ingrese una palabra, (x para salir) " i
    if [[ $i =~ [xX] ]]; then
        break
    echo $i
    fi
done
done
[ $# -eq 0 ] && echo "El script solo funciona con argumentos"

