#!/bin/bash

cont1=0
cont2=0
cont3=0
for i in $@; do
    if [[ $(($i%2)) -eq 0 ]]; then
        ((cont1++))
    fi
    if [[ $i -gt 0 ]]; then
        ((cont2++))
    fi
    if [[ ${#i} -eq 3 ]]; then
        ((cont3++))
    fi
done
echo "Hay $cont1 numeros pares, $cont2 numeros positivos, $cont3 numeros de tres cifras"